#!/bin/bash

sudo systemctl enable httpd
sudo systemctl restart httpd
sudo mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
sudo systemctl enable mysqld
sudo systemctl start mysqld

#sudo sed -i 's|#LoadModule mpm_event_module modules/mod_mpm_event.so|LoadModule mpm_event_module modules/mod_mpm_event.so|' /etc/httpd/conf/httpd.conf
sudo sed -i 's|#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so|LoadModule mpm_prefork_module modules/mod_mpm_prefork.so|' /etc/httpd/conf/httpd.conf

echo "" | sudo tee -a /etc/httpd/conf/httpd.conf
sudo tee -a /etc/httpd/conf/httpd.conf <<EOF
LoadModule php_module modules/libphp.so
AddHandler php-script php
Include conf/extra/php_module.conf
EOF

sudo systemctl restart httpd
sudo sed -i 's|;extension=mysqli|extension=mysqli|' /etc/php/php.ini
sudo sed -i 's|;extension=pdo_mysql|extension=pdo_mysql|' /etc/php/php.ini
sudo sed -i 's|;extension=bz2|extension=bz2|' /etc/php/php.ini

sudo tee -a /etc/httpd/conf/extra/phpmyadmin.conf <<EOF
Alias /phpmyadmin "/usr/share/webapps/phpMyAdmin"
<Directory "/usr/share/webapps/phpMyAdmin">
    DirectoryIndex index.php
    AllowOverride All
    Options FollowSymlinks
    Require all granted
</Directory>
EOF

sudo tee -a /etc/httpd/conf/httpd.conf <<EOF

Include conf/extra/phpmyadmin.conf
EOF
sudo systemctl restart httpd
